services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    ports:
      - "8080:8080"

    command: ["start-dev"]

  django:
    build: .
    ports:
      - "8000:8000"

  #coldfront:

